url: https://joycekimberly.github.io/SoniaLynnBjornsen
baseurl: SoniaLynnBjornsen
permalink: pretty
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Sonia Lynn Bjornsen"

gems:
  - jekyll-seo-tag

seo:
  type: Person
