url: https://joycekimberly.github.io/SoniaLynnBjornsen
baseurl: SoniaLynnBjornsen
permalink: pretty
markdown: kramdown
include: ["_pages"]

sass:
    sass_dir: SoniaLynnBjornsen/_sass

plugins:
  - jekyll-admin

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Sonia Lynn Bjornsen"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: ""
